In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('C:\\Users\\Shankar.K\\Downloads\\INDIAvi.csv')

In [3]:
type(data)

pandas.core.frame.DataFrame

In [21]:
data.info() #concise summary

<class 'pandas.core.frame.DataFrame'>
Index: 33089 entries, 0 to 37330
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                33089 non-null  object
 1   trending_date           33089 non-null  object
 2   title                   33089 non-null  object
 3   channel_title           33089 non-null  object
 4   category_id             33089 non-null  int64
 5   publish_time            33089 non-null  object
 6   tags                    33089 non-null  object
 7   views                   33089 non-null  int64
 8   likes                   33089 non-null  int64
 9   dislikes                33089 non-null  int64
 10  comment_count           33089 non-null  int64
 11  thumbnail_link          33089 non-null  object
 12  comments_disabled       33089 non-null  bool
 13  ratings_disabled        33089 non-null  bool
 14  video_error_or_removed  33089 non-null  bool
 15  description             32562 non-null  object
dtypes: bool(3), int64(5), object(8)
memory usage: 3.6+ MB

In [5]:
data.describe() #descriptive statistics

        category_id         views         likes      dislikes  comment_count
count  37352.000000  3.735200e+04  3.735200e+04  3.735200e+04    37352.00000
mean      21.576596  1.060478e+06  2.708272e+04  1.665082e+03     2676.99743
std        6.556593  3.184932e+06  9.714510e+04  1.607617e+04    14868.31713
min        1.000000  4.024000e+03  0.000000e+00  0.000000e+00        0.00000
25%       23.000000  1.239155e+05  8.640000e+02  1.080000e+02       81.00000
50%       24.000000  3.045860e+05  3.069000e+03  3.260000e+02      329.00000
75%       24.000000  7.992912e+05  1.377425e+04  1.019250e+03     1285.00000
max       43.000000  1.254322e+08  2.912710e+06  1.545017e+06   827755.00000

In [6]:
data = data.drop_duplicates()
data

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,kzwfHumJyYc,17.14.11,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,1,2017-11-12T12:20:39.000Z,"sharry mann|""sharry mann new song""|""sharry man...",1096327,33966,798,882,https://i.ytimg.com/vi/kzwfHumJyYc/default.jpg,False,False,False,Presenting Sharry Mann latest Punjabi Song Cu...
1,zUZ1z7FwLc8,17.14.11,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं...",HJ NEWS,25,2017-11-13T05:43:56.000Z,"पीरियड्स के समय|""पेट पर पति करता ऐसा""|""देखकर द...",590101,735,904,0,https://i.ytimg.com/vi/zUZ1z7FwLc8/default.jpg,True,False,False,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं..."
2,10L1hZ9qa58,17.14.11,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,TFPC,24,2017-11-12T15:48:08.000Z,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,473988,2011,243,149,https://i.ytimg.com/vi/10L1hZ9qa58/default.jpg,False,False,False,Watch Stylish Star Allu Arjun @ ChaySam Weddin...
3,N1vE8iiEg64,17.14.11,Eruma Saani | Tamil vs English,Eruma Saani,23,2017-11-12T07:08:48.000Z,"Eruma Saani|""Tamil Comedy Videos""|""Films""|""Mov...",1242680,70353,1624,2684,https://i.ytimg.com/vi/N1vE8iiEg64/default.jpg,False,False,False,This video showcases the difference between pe...
4,kJzGH0PVQHQ,17.14.11,why Samantha became EMOTIONAL @ Samantha naga ...,Filmylooks,24,2017-11-13T01:14:16.000Z,"Filmylooks|""latest news""|""telugu movies""|""telu...",464015,492,293,66,https://i.ytimg.com/vi/kJzGH0PVQHQ/default.jpg,False,False,False,why Samantha became EMOTIONAL @ Samantha naga ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37300,UPbi1oG5UPg,18.14.06,Engineering Girls | Web Series | S01E02 - Ghar...,The Timeliners,24,2018-06-08T13:54:39.000Z,"funny videos|""hotels""|""comedy""|""comedy video""|...",2675706,96485,4181,6634,https://i.ytimg.com/vi/UPbi1oG5UPg/default.jpg,False,False,False,Maggu is preparing for Sharda University inter...
37301,3MTCSll3KGU,18.14.06,Rusev vs. Samoa Joe - with Special Guest Refer...,WWE,17,2018-06-13T03:09:21.000Z,"wwe|""world wrestling entertainment""|""wrestling...",770873,13316,552,1175,https://i.ytimg.com/vi/3MTCSll3KGU/default.jpg,False,False,False,The Miz serves as special guest referee in thi...
37302,TIE92mUvSsw,18.14.06,Dhadak | Official Trailer | Janhvi & Ishaan | ...,Dharma Productions,1,2018-06-11T06:50:41.000Z,"Dharma|""Dharma Productions""|""Dhadak""|""Janhvi K...",27696924,468472,60025,48740,https://i.ytimg.com/vi/TIE92mUvSsw/default.jpg,False,False,False,"When two worlds collide, they become oneDhadak..."
37319,1-0mS2ZBrQk,18.14.06,What If PubG Was Made In India ?,Angry Prash,23,2018-06-11T08:37:21.000Z,"pubg|""PlayerUnknown's Battlegrounds""|""pubg mob...",1214423,85601,4677,7628,https://i.ytimg.com/vi/1-0mS2ZBrQk/default.jpg,False,False,False,This funny video is about what if players unkn...
37330,K10YIAokjvE,18.14.06,Funny Ramzan Scenes Part - 2 | Hyderabadi Come...,Warangal Diaries,23,2018-06-13T10:16:21.000Z,"warangal diaries|""latest""|""funny""|""comedy""|""Ba...",132055,11170,393,2107,https://i.ytimg.com/vi/K10YIAokjvE/default.jpg,False,False,False,(Earphone Use Is Recommended)!!Funny Ramzan Sc...

In [7]:
data.isnull()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37300,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
37301,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
37302,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
37319,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
37330,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
data.isnull().sum()

video_id                    0
trending_date               0
title                       0
channel_title               0
category_id                 0
publish_time                0
tags                        0
views                       0
likes                       0
dislikes                    0
comment_count               0
thumbnail_link              0
comments_disabled           0
ratings_disabled            0
video_error_or_removed      0
description               527
dtype: int64

In [9]:
data.notnull()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37300,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
37301,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
37302,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
37319,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
37330,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [10]:
data.isnull().sum().sum()

527

In [11]:
data2 = data.fillna(value=0)
data2

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,kzwfHumJyYc,17.14.11,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,1,2017-11-12T12:20:39.000Z,"sharry mann|""sharry mann new song""|""sharry man...",1096327,33966,798,882,https://i.ytimg.com/vi/kzwfHumJyYc/default.jpg,False,False,False,Presenting Sharry Mann latest Punjabi Song Cu...
1,zUZ1z7FwLc8,17.14.11,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं...",HJ NEWS,25,2017-11-13T05:43:56.000Z,"पीरियड्स के समय|""पेट पर पति करता ऐसा""|""देखकर द...",590101,735,904,0,https://i.ytimg.com/vi/zUZ1z7FwLc8/default.jpg,True,False,False,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं..."
2,10L1hZ9qa58,17.14.11,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,TFPC,24,2017-11-12T15:48:08.000Z,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,473988,2011,243,149,https://i.ytimg.com/vi/10L1hZ9qa58/default.jpg,False,False,False,Watch Stylish Star Allu Arjun @ ChaySam Weddin...
3,N1vE8iiEg64,17.14.11,Eruma Saani | Tamil vs English,Eruma Saani,23,2017-11-12T07:08:48.000Z,"Eruma Saani|""Tamil Comedy Videos""|""Films""|""Mov...",1242680,70353,1624,2684,https://i.ytimg.com/vi/N1vE8iiEg64/default.jpg,False,False,False,This video showcases the difference between pe...
4,kJzGH0PVQHQ,17.14.11,why Samantha became EMOTIONAL @ Samantha naga ...,Filmylooks,24,2017-11-13T01:14:16.000Z,"Filmylooks|""latest news""|""telugu movies""|""telu...",464015,492,293,66,https://i.ytimg.com/vi/kJzGH0PVQHQ/default.jpg,False,False,False,why Samantha became EMOTIONAL @ Samantha naga ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37300,UPbi1oG5UPg,18.14.06,Engineering Girls | Web Series | S01E02 - Ghar...,The Timeliners,24,2018-06-08T13:54:39.000Z,"funny videos|""hotels""|""comedy""|""comedy video""|...",2675706,96485,4181,6634,https://i.ytimg.com/vi/UPbi1oG5UPg/default.jpg,False,False,False,Maggu is preparing for Sharda University inter...
37301,3MTCSll3KGU,18.14.06,Rusev vs. Samoa Joe - with Special Guest Refer...,WWE,17,2018-06-13T03:09:21.000Z,"wwe|""world wrestling entertainment""|""wrestling...",770873,13316,552,1175,https://i.ytimg.com/vi/3MTCSll3KGU/default.jpg,False,False,False,The Miz serves as special guest referee in thi...
37302,TIE92mUvSsw,18.14.06,Dhadak | Official Trailer | Janhvi & Ishaan | ...,Dharma Productions,1,2018-06-11T06:50:41.000Z,"Dharma|""Dharma Productions""|""Dhadak""|""Janhvi K...",27696924,468472,60025,48740,https://i.ytimg.com/vi/TIE92mUvSsw/default.jpg,False,False,False,"When two worlds collide, they become oneDhadak..."
37319,1-0mS2ZBrQk,18.14.06,What If PubG Was Made In India ?,Angry Prash,23,2018-06-11T08:37:21.000Z,"pubg|""PlayerUnknown's Battlegrounds""|""pubg mob...",1214423,85601,4677,7628,https://i.ytimg.com/vi/1-0mS2ZBrQk/default.jpg,False,False,False,This funny video is about what if players unkn...
37330,K10YIAokjvE,18.14.06,Funny Ramzan Scenes Part - 2 | Hyderabadi Come...,Warangal Diaries,23,2018-06-13T10:16:21.000Z,"warangal diaries|""latest""|""funny""|""comedy""|""Ba...",132055,11170,393,2107,https://i.ytimg.com/vi/K10YIAokjvE/default.jpg,False,False,False,(Earphone Use Is Recommended)!!Funny Ramzan Sc...

In [12]:
data2.isnull().sum().sum()

0

In [23]:
data3 = data.fillna(method='pad')
data3

C:\Users\Shankar.K\AppData\Local\Temp\ipykernel_464\3463156805.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data3 = data.fillna(method='pad')#second method (forward filling method)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,kzwfHumJyYc,17.14.11,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,1,2017-11-12T12:20:39.000Z,"sharry mann|""sharry mann new song""|""sharry man...",1096327,33966,798,882,https://i.ytimg.com/vi/kzwfHumJyYc/default.jpg,False,False,False,Presenting Sharry Mann latest Punjabi Song Cu...
1,zUZ1z7FwLc8,17.14.11,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं...",HJ NEWS,25,2017-11-13T05:43:56.000Z,"पीरियड्स के समय|""पेट पर पति करता ऐसा""|""देखकर द...",590101,735,904,0,https://i.ytimg.com/vi/zUZ1z7FwLc8/default.jpg,True,False,False,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं..."
2,10L1hZ9qa58,17.14.11,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,TFPC,24,2017-11-12T15:48:08.000Z,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,473988,2011,243,149,https://i.ytimg.com/vi/10L1hZ9qa58/default.jpg,False,False,False,Watch Stylish Star Allu Arjun @ ChaySam Weddin...
3,N1vE8iiEg64,17.14.11,Eruma Saani | Tamil vs English,Eruma Saani,23,2017-11-12T07:08:48.000Z,"Eruma Saani|""Tamil Comedy Videos""|""Films""|""Mov...",1242680,70353,1624,2684,https://i.ytimg.com/vi/N1vE8iiEg64/default.jpg,False,False,False,This video showcases the difference between pe...
4,kJzGH0PVQHQ,17.14.11,why Samantha became EMOTIONAL @ Samantha naga ...,Filmylooks,24,2017-11-13T01:14:16.000Z,"Filmylooks|""latest news""|""telugu movies""|""telu...",464015,492,293,66,https://i.ytimg.com/vi/kJzGH0PVQHQ/default.jpg,False,False,False,why Samantha became EMOTIONAL @ Samantha naga ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37300,UPbi1oG5UPg,18.14.06,Engineering Girls | Web Series | S01E02 - Ghar...,The Timeliners,24,2018-06-08T13:54:39.000Z,"funny videos|""hotels""|""comedy""|""comedy video""|...",2675706,96485,4181,6634,https://i.ytimg.com/vi/UPbi1oG5UPg/default.jpg,False,False,False,Maggu is preparing for Sharda University inter...
37301,3MTCSll3KGU,18.14.06,Rusev vs. Samoa Joe - with Special Guest Refer...,WWE,17,2018-06-13T03:09:21.000Z,"wwe|""world wrestling entertainment""|""wrestling...",770873,13316,552,1175,https://i.ytimg.com/vi/3MTCSll3KGU/default.jpg,False,False,False,The Miz serves as special guest referee in thi...
37302,TIE92mUvSsw,18.14.06,Dhadak | Official Trailer | Janhvi & Ishaan | ...,Dharma Productions,1,2018-06-11T06:50:41.000Z,"Dharma|""Dharma Productions""|""Dhadak""|""Janhvi K...",27696924,468472,60025,48740,https://i.ytimg.com/vi/TIE92mUvSsw/default.jpg,False,False,False,"When two worlds collide, they become oneDhadak..."
37319,1-0mS2ZBrQk,18.14.06,What If PubG Was Made In India ?,Angry Prash,23,2018-06-11T08:37:21.000Z,"pubg|""PlayerUnknown's Battlegrounds""|""pubg mob...",1214423,85601,4677,7628,https://i.ytimg.com/vi/1-0mS2ZBrQk/default.jpg,False,False,False,This funny video is about what if players unkn...
37330,K10YIAokjvE,18.14.06,Funny Ramzan Scenes Part - 2 | Hyderabadi Come...,Warangal Diaries,23,2018-06-13T10:16:21.000Z,"warangal diaries|""latest""|""funny""|""comedy""|""Ba...",132055,11170,393,2107,https://i.ytimg.com/vi/K10YIAokjvE/default.jpg,False,False,False,(Earphone Use Is Recommended)!!Funny Ramzan Sc...

In [14]:
#filling null values with the next value
data4=data.fillna(method='bfill')
data4

C:\Users\Shankar.K\AppData\Local\Temp\ipykernel_464\1502939909.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data4=data.fillna(method='bfill')

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,kzwfHumJyYc,17.14.11,Sharry Mann: Cute Munda ( Song Teaser) | Parmi...,Lokdhun Punjabi,1,2017-11-12T12:20:39.000Z,"sharry mann|""sharry mann new song""|""sharry man...",1096327,33966,798,882,https://i.ytimg.com/vi/kzwfHumJyYc/default.jpg,False,False,False,Presenting Sharry Mann latest Punjabi Song Cu...
1,zUZ1z7FwLc8,17.14.11,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं...",HJ NEWS,25,2017-11-13T05:43:56.000Z,"पीरियड्स के समय|""पेट पर पति करता ऐसा""|""देखकर द...",590101,735,904,0,https://i.ytimg.com/vi/zUZ1z7FwLc8/default.jpg,True,False,False,"पीरियड्स के समय, पेट पर पति करता ऐसा, देखकर दं..."
2,10L1hZ9qa58,17.14.11,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,TFPC,24,2017-11-12T15:48:08.000Z,Stylish Star Allu Arjun @ ChaySam Wedding Rece...,473988,2011,243,149,https://i.ytimg.com/vi/10L1hZ9qa58/default.jpg,False,False,False,Watch Stylish Star Allu Arjun @ ChaySam Weddin...
3,N1vE8iiEg64,17.14.11,Eruma Saani | Tamil vs English,Eruma Saani,23,2017-11-12T07:08:48.000Z,"Eruma Saani|""Tamil Comedy Videos""|""Films""|""Mov...",1242680,70353,1624,2684,https://i.ytimg.com/vi/N1vE8iiEg64/default.jpg,False,False,False,This video showcases the difference between pe...
4,kJzGH0PVQHQ,17.14.11,why Samantha became EMOTIONAL @ Samantha naga ...,Filmylooks,24,2017-11-13T01:14:16.000Z,"Filmylooks|""latest news""|""telugu movies""|""telu...",464015,492,293,66,https://i.ytimg.com/vi/kJzGH0PVQHQ/default.jpg,False,False,False,why Samantha became EMOTIONAL @ Samantha naga ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37300,UPbi1oG5UPg,18.14.06,Engineering Girls | Web Series | S01E02 - Ghar...,The Timeliners,24,2018-06-08T13:54:39.000Z,"funny videos|""hotels""|""comedy""|""comedy video""|...",2675706,96485,4181,6634,https://i.ytimg.com/vi/UPbi1oG5UPg/default.jpg,False,False,False,Maggu is preparing for Sharda University inter...
37301,3MTCSll3KGU,18.14.06,Rusev vs. Samoa Joe - with Special Guest Refer...,WWE,17,2018-06-13T03:09:21.000Z,"wwe|""world wrestling entertainment""|""wrestling...",770873,13316,552,1175,https://i.ytimg.com/vi/3MTCSll3KGU/default.jpg,False,False,False,The Miz serves as special guest referee in thi...
37302,TIE92mUvSsw,18.14.06,Dhadak | Official Trailer | Janhvi & Ishaan | ...,Dharma Productions,1,2018-06-11T06:50:41.000Z,"Dharma|""Dharma Productions""|""Dhadak""|""Janhvi K...",27696924,468472,60025,48740,https://i.ytimg.com/vi/TIE92mUvSsw/default.jpg,False,False,False,"When two worlds collide, they become oneDhadak..."
37319,1-0mS2ZBrQk,18.14.06,What If PubG Was Made In India ?,Angry Prash,23,2018-06-11T08:37:21.000Z,"pubg|""PlayerUnknown's Battlegrounds""|""pubg mob...",1214423,85601,4677,7628,https://i.ytimg.com/vi/1-0mS2ZBrQk/default.jpg,False,False,False,This funny video is about what if players unkn...
37330,K10YIAokjvE,18.14.06,Funny Ramzan Scenes Part - 2 | Hyderabadi Come...,Warangal Diaries,23,2018-06-13T10:16:21.000Z,"warangal diaries|""latest""|""funny""|""comedy""|""Ba...",132055,11170,393,2107,https://i.ytimg.com/vi/K10YIAokjvE/default.jpg,False,False,False,(Earphone Use Is Recommended)!!Funny Ramzan Sc...

In [15]:
import numpy as np
from scipy import stats

In [16]:
#detect the outliers using IQR
data2.columns

Index(['video_id', 'trending_date', 'title', 'channel_title', 'category_id',
       'publish_time', 'tags', 'views', 'likes', 'dislikes', 'comment_count',
       'thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description'],
      dtype='object')

In [17]:
data2.drop(['video_id', 'trending_date', 'title', 'channel_title','publish_time', 'tags','thumbnail_link', 'comments_disabled', 'ratings_disabled',
       'video_error_or_removed', 'description'], axis=1, inplace=True)
data2.columns

Index(['category_id', 'views', 'likes', 'dislikes', 'comment_count'], dtype='object')

In [18]:
Q1=data2.quantile(0.25)
Q3=data2.quantile(0.75)
IQR=Q3-Q1
print(IQR)

category_id           1.0
views            619303.0
likes             11224.0
dislikes            834.0
comment_count      1097.0
dtype: float64

In [19]:
data2=data2[~((data2< (Q1-1.5*IQR) ) | (data2>(Q3+1.5*IQR)) ) .any(axis=1)]
data2

       category_id   views  likes  dislikes  comment_count
1               25  590101    735       904              0
2               24  473988   2011       243            149
4               24  464015    492       293             66
8               24  118223    520        53             23
12              25  156085    716        53              0
...            ...     ...    ...       ...            ...
37291           24  277211    869       225             56
37295           23   29536   1559        64             94
37296           22  186197    855        86             25
37298           25  145452    627       100             34
37330           23  132055  11170       393           2107

[20698 rows x 5 columns]

In [22]:
data2.describe()

        category_id         views         likes      dislikes  comment_count
count  20698.000000  2.069800e+04  20698.000000  20698.000000   20698.000000
mean      23.935549  2.922204e+05   3251.538796    317.437579     344.873997
std        0.825911  2.899499e+05   4794.185851    367.714377     471.985847
min       22.000000  4.024000e+03      0.000000      0.000000       0.000000
25%       24.000000  9.444825e+04    483.000000     72.000000      43.000000
50%       24.000000  1.890815e+05   1330.500000    181.000000     154.000000
75%       24.000000  3.828452e+05   3752.000000    419.000000     443.000000
max       25.000000  1.660490e+06  28823.000000   2183.000000    2814.000000